name: digitos
description: A game of numbers.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.0.6+6

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^5.2.0
  cupertino_icons: ^1.0.6
  go_router: ^13.0.0
  logging: ^1.2.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.15.3
  flutter_native_splash: ^2.3.10
  flutter_dotenv: ^5.1.0
  graphql_flutter: ^5.2.0-beta.6
  get_it: ^7.6.7
  tuple: ^2.0.2
  path_provider: ^2.1.2
  share: ^2.0.4

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  test: ^1.24.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/music/
    - assets/sfx/
    - .env

  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/fonts/Permanent_Marker/PermanentMarker-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/icon-adaptive-foreground.png"
