// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgC43k0z5R0EAQM-so4hSI5owKDPMe_-k',
    appId: '1:540649544846:web:42eb8960964a77b318bddf',
    messagingSenderId: '540649544846',
    projectId: 'digitos-2ba0b',
    authDomain: 'digitos-2ba0b.firebaseapp.com',
    databaseURL: 'https://digitos-2ba0b-default-rtdb.firebaseio.com',
    storageBucket: 'digitos-2ba0b.appspot.com',
    measurementId: 'G-0S34JC82HX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANH9miWbWOW368glX4cKkWp_j5ZLWn_6E',
    appId: '1:540649544846:android:e4d8c91fbe055f0718bddf',
    messagingSenderId: '540649544846',
    projectId: 'digitos-2ba0b',
    databaseURL: 'https://digitos-2ba0b-default-rtdb.firebaseio.com',
    storageBucket: 'digitos-2ba0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHv1WrlCcJp8cN5RH7zQ0GsVaA6nL--a4',
    appId: '1:540649544846:ios:cece2f96db63515d18bddf',
    messagingSenderId: '540649544846',
    projectId: 'digitos-2ba0b',
    databaseURL: 'https://digitos-2ba0b-default-rtdb.firebaseio.com',
    storageBucket: 'digitos-2ba0b.appspot.com',
    iosClientId: '540649544846-8h14dr2hqbbnv56bbho5jo9gt4pt8tiq.apps.googleusercontent.com',
    iosBundleId: 'com.digitos.digitos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHv1WrlCcJp8cN5RH7zQ0GsVaA6nL--a4',
    appId: '1:540649544846:ios:9ffbe74175e0eee618bddf',
    messagingSenderId: '540649544846',
    projectId: 'digitos-2ba0b',
    databaseURL: 'https://digitos-2ba0b-default-rtdb.firebaseio.com',
    storageBucket: 'digitos-2ba0b.appspot.com',
    iosBundleId: 'com.example.basic.RunnerTests',
  );
}
